public class calculation {
    
    public static void addition(integer a,integer b)
    {
        integer add = a+b;
        System.debug('Addition is : '+add);
    }
    
    public static void subtraction(integer a,integer b)
    {
        integer sub = a-b;
        System.debug('Subtraction is : '+sub);
    }
    
    public static void multiplication(integer a,integer b)
    {
        integer multi = a*b;
        System.debug('Multiplication is : '+multi);
    }
    
    public static void division(integer a,integer b)
    {
        integer div = a/b;
        System.debug('Division is : '+div);
    }

}